### ISSUE TITLE
雛形の作成

### ISSUE THREAD

**Issue by hyperkinoko** [hyperkinoko/dynamic-document#1]
main ブランチへのfirst commit
`create-react`ツールでinitして，それをpushしてください

**Comment by hyperkinoko** [comment]
このissueに関しては，PRを作成せずにmainにpushしてください

**Comment by yu2799** [comment]
`npx create-react-app dynamic-document --template typescript`直後のファイルをpushしました

**Comment by hyperkinoko** [comment]
LGTM
