### ISSUE TITLE
Modelを作成し，定義に沿ってドキュメント間のhyperlinkを成立させる

### ISSUE THREAD

**Issue by hyperkinoko** [hyperkinoko/dynamic-document#3]
ボタンを押すと適切なドキュメントに移動する。
ボタンは見た目だけで，実質リンクでOK(onClickにする必要なし)

- [x] modelの作成（Reactのお作法がわからないんですが，MVCでいうところのmodelと理解してください）
- [x] modelにデータを突っ込むと，そのとおりに遷移して，データ通りのmdが表示される

**Comment by hyperkinoko** [comment]
![Untitled (3)](https://user-images.githubusercontent.com/5547149/162549135-a5efd3fe-b7c7-4968-bd20-edf546e185b8.jpg)
こういうのを作りたい

**Comment by hyperkinoko** [comment]
markdownは直接記述のみでうまく動けばOK

**Comment by hyperkinoko** [comment]
上の図にあるdocumentオブジェクトのイメージです。ただし，名前がdocumentなのはイケてない気がする。（JSのdocumentオブジェクトとかぶりそう・・・）いい感じの名前付けをしてほしいです。

```
{
  id: hogehoge
  url: パーマリンク的な
  lead: マークダウン
  content: マークダウン
  question: マークダウン
  options:[
    {
      label: 'はい',
      next: 「はい」をクリックしたときに遷移する
             documentオブジェクト
    },
    {
      label: 'はい',
      next: 「はい」をクリックしたときに遷移する
             documentオブジェクト
    },
    {
      label: 'はい',
      next: 「はい」をクリックしたときに遷移する
             documentオブジェクト
    }
  ]
}
```

**Comment by yu2799** [comment]
@hyperkinoko 
> markdownは直接記述のみでうまく動けばOK

これよくわかってないんですけど，すでに記述されたmarkdownが表示できればokって解釈で問題ないですか？

> ボタンを押すと適切なドキュメントに移動する。 ボタンは見た目だけで，実質リンクでOK(onClickにする必要なし)
> 
> * [ ]  modelの作成（Reactのお作法がわからないんですが，MVCでいうところのmodelと理解してください）
> * [x]  modelにデータを突っ込むと，そのとおりに遷移して，データ通りのmdが表示される

ボタンを押したら，その遷移先となるurlをオブジェクトから取得して遷移させるといった処理がmodelって解釈で問題ないですか？

**Comment by hyperkinoko** [comment]
@yu2799 

> これよくわかってないんですけど，すでに記述されたmarkdownが表示できればokって解釈で問題ないですか？

オブジェクトに直接マークダウンが記述されている状態のことです。例えば以下のような。

```
{
  id: hogehoge,
  url: パーマリンク的な,
  lead: 'これは**リード文**です',
  content: `Just a link: https://reactjs.com.
  ~~取り消し線~~
  * [ ] hoge
  * [x] piyo
  `,
  question: `## 質問
ほげほげにこたえてください
`,
  options:[
    {
      label: 'はい',
      next: 「はい」をクリックしたときに遷移する
             documentオブジェクト
    },
    {
      label: 'はい',
      next: 「はい」をクリックしたときに遷移する
             documentオブジェクト
    },
    {
      label: 'はい',
      next: 「はい」をクリックしたときに遷移する
             documentオブジェクト
    }
  ]
}
```

**Comment by hyperkinoko** [comment]
@yu2799 
> ボタンを押したら，その遷移先となるurlをオブジェクトから取得して遷移させるといった処理がmodelって解釈で問題ないですか？

処理はmodelじゃないので，なんか違うかも・・・？

**Comment by hyperkinoko** [comment]
@yu2799 
Reactで作り始めちゃったので，私Reactのお作法全然知らなくて（読むくらいならできます）
一度ペアプロでもしてみますか？

**Comment by hyperkinoko** [comment]
思った以上によくできてる！！ありがとう！！
